name: Build on PR

on:
  pull_request:
    branches:
      - dev
      - production
      - hotfix*
      - main
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: latest
          run_install: false

      - name: Install Dependencies
        run: pnpm install

      - name: Build # React Build
        run: pnpm run build
